#pragma once
#include <Arduino.h>

#define THINKING_FRAMES 68

extern const unsigned char _thinking_000[] PROGMEM;
extern const unsigned char _thinking_001[] PROGMEM;
extern const unsigned char _thinking_002[] PROGMEM;
extern const unsigned char _thinking_003[] PROGMEM;
extern const unsigned char _thinking_004[] PROGMEM;
extern const unsigned char _thinking_005[] PROGMEM;
extern const unsigned char _thinking_006[] PROGMEM;
extern const unsigned char _thinking_007[] PROGMEM;
extern const unsigned char _thinking_008[] PROGMEM;
extern const unsigned char _thinking_009[] PROGMEM;
extern const unsigned char _thinking_010[] PROGMEM;
extern const unsigned char _thinking_011[] PROGMEM;
extern const unsigned char _thinking_012[] PROGMEM;
extern const unsigned char _thinking_013[] PROGMEM;
extern const unsigned char _thinking_014[] PROGMEM;
extern const unsigned char _thinking_015[] PROGMEM;
extern const unsigned char _thinking_016[] PROGMEM;
extern const unsigned char _thinking_017[] PROGMEM;
extern const unsigned char _thinking_018[] PROGMEM;
extern const unsigned char _thinking_019[] PROGMEM;
extern const unsigned char _thinking_020[] PROGMEM;
extern const unsigned char _thinking_021[] PROGMEM;
extern const unsigned char _thinking_022[] PROGMEM;
extern const unsigned char _thinking_023[] PROGMEM;
extern const unsigned char _thinking_024[] PROGMEM;
extern const unsigned char _thinking_025[] PROGMEM;
extern const unsigned char _thinking_026[] PROGMEM;
extern const unsigned char _thinking_027[] PROGMEM;
extern const unsigned char _thinking_028[] PROGMEM;
extern const unsigned char _thinking_029[] PROGMEM;
extern const unsigned char _thinking_030[] PROGMEM;
extern const unsigned char _thinking_031[] PROGMEM;
extern const unsigned char _thinking_032[] PROGMEM;
extern const unsigned char _thinking_033[] PROGMEM;
extern const unsigned char _thinking_034[] PROGMEM;
extern const unsigned char _thinking_035[] PROGMEM;
extern const unsigned char _thinking_036[] PROGMEM;
extern const unsigned char _thinking_037[] PROGMEM;
extern const unsigned char _thinking_038[] PROGMEM;
extern const unsigned char _thinking_039[] PROGMEM;
extern const unsigned char _thinking_040[] PROGMEM;
extern const unsigned char _thinking_041[] PROGMEM;
extern const unsigned char _thinking_042[] PROGMEM;
extern const unsigned char _thinking_043[] PROGMEM;
extern const unsigned char _thinking_044[] PROGMEM;
extern const unsigned char _thinking_045[] PROGMEM;
extern const unsigned char _thinking_046[] PROGMEM;
extern const unsigned char _thinking_047[] PROGMEM;
extern const unsigned char _thinking_048[] PROGMEM;
extern const unsigned char _thinking_049[] PROGMEM;
extern const unsigned char _thinking_050[] PROGMEM;
extern const unsigned char _thinking_051[] PROGMEM;
extern const unsigned char _thinking_052[] PROGMEM;
extern const unsigned char _thinking_053[] PROGMEM;
extern const unsigned char _thinking_054[] PROGMEM;
extern const unsigned char _thinking_055[] PROGMEM;
extern const unsigned char _thinking_056[] PROGMEM;
extern const unsigned char _thinking_057[] PROGMEM;
extern const unsigned char _thinking_058[] PROGMEM;
extern const unsigned char _thinking_059[] PROGMEM;
extern const unsigned char _thinking_060[] PROGMEM;
extern const unsigned char _thinking_061[] PROGMEM;
extern const unsigned char _thinking_062[] PROGMEM;
extern const unsigned char _thinking_063[] PROGMEM;
extern const unsigned char _thinking_064[] PROGMEM;
extern const unsigned char _thinking_065[] PROGMEM;
extern const unsigned char _thinking_066[] PROGMEM;
extern const unsigned char _thinking_067[] PROGMEM;

extern const unsigned char* const  thinking_frames[] PROGMEM = {};
